# Generated by Django 4.2.11 on 2024-05-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='url title', max_length=300, verbose_name='نام در url'),
            preserve_default=False,
        ),
    ]
