# Generated by Django 4.2.11 on 2024-05-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0008_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقالات'},
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='تایید'),
        ),
    ]
